sudo: false
dist: trusty

language: python
python: 3.6
cache: pip

addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

install:
  - python -m pip install -U pip
  - psql -U postgres -c 'create database "jarbas";'
  - python -m pip install -r requirements-dev.txt coveralls
  - ./rosie/setup

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --no-input

script:
  - coverage run manage.py test
  - cd rosie && coverage run rosie.py test && python rosie.py run federal_senate

after_success:
  - coveralls
