version: '3'
services:

  rosie:
    build:
      context: rosie
    volumes:
      - /tmp/serenata-data:/tmp/serenata-data
      - ./rosie:/code

  django:
    image: serenata/django
    depends_on:
      - elm
      - postgres
      - tasks
    environment:
      - NEW_RELIC_APP_NAME=Jarbas (Django); Jarbas (Combined)
    env_file:
      - .env
    hostname: django
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./contrib/data:/mnt/data

  tasks:
    image: serenata/django
    environment:
      - NEW_RELIC_APP_NAME=Jarbas (Celery); Jarbas (Combined)
    env_file:
      - .env
    depends_on:
      - queue
    command: ["newrelic-admin", "run-program", "celery", "worker", "--app", "jarbas"]
    volumes:
      - .:/code
    hostname: tasks

  elm:
    command: ["npm", "run", "watch"]
    image: serenata/elm
    volumes:
      - ./jarbas:/code/jarbas
    hostname: elm

  queue:
    image: rabbitmq:3.7.3-alpine
    hostname: queue

  postgres:
    image: postgres:10.3-alpine
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"

  research:
    build:
      context: research
      args:
        - AMAZON_BUCKET
        - AMAZON_ENDPOINT
        - AMAZON_REGION
    env_file:
      - .env
    volumes:
      - ./research:/mnt/code
    hostname: research
