version: '3'
services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-public:/usr/share/nginx/html
    hostname: proxy

  proxy-certs:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-public:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: proxy
    hostname: proxy-certs

  django:
    env_file:
      - .env.prod
    networks:
      - backend
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: ${VIRTUAL_HOST_WEB}
    depends_on:
      - memcached
    expose:
      - "8000"
    volumes:
      - assets:/code/staticfiles
    command: ["gunicorn", "jarbas.wsgi:application", "--reload", "--bind", "0.0.0.0:8000", "--workers", "2"]

  tasks:
    env_file:
      - .env
    networks:
      - backend
    environment:
      - DEBUG=False

  queue:
    networks:
      - backend

  elm:
    command: ["npm", "run", "assets"]
    volumes:
      - assets:/code/jarbas/layers/static

  memcached:
    image: memcached:1.5.1-alpine
    networks:
      - backend
    hostname: memcached

  nginx:
    image: datasciencebr/jarbas-server
    networks:
      - backend
    depends_on:
      - django
    volumes:
      - assets:/code/staticfiles
    environment:
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_WEB}
      VIRTUAL_HOST: ${VIRTUAL_HOST_WEB}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-contato@serenata.ai}
      HTTPS_METHOD: ${HTTPS_METHOD:-redirect}
      VIRTUAL_PROTO: http
    hostname: nginx

  logspout:
    image: gliderlabs/logspout:v3.2.4
    restart: always
    env_file:
      - .env
    command: ${LOGGING_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  assets:
  proxy-certs:
  proxy-vhost:
  proxy-public:

networks:
  backend:
