apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres
    database: jarbas
    user: jarbas
    secureJsonData:
      password: "mysecretpassword"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 904 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
